insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (114241, 'Becca', 'Project Manager', 'Female', 37235);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (106443, 'Jehu', 'Accounting Assistant I', 'Male', 34059);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (536190, 'Ermengarde', 'Assistant Manager', 'Female', 23297);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (425219, 'Bryn', 'Mechanical Systems Engineer', 'Male', 21711);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (179922, 'Anna', 'Operator', 'Female', 25927);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (966305, 'Cordelia', 'Internal Auditor', 'Female', 14379);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (535318, 'Wilburt', 'Chief Design Engineer', 'Male', 34721);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (368274, 'Aurthur', 'Programmer Analyst IV', 'Male', 18670);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (966414, 'Dick', 'Structural Analysis Engineer', 'Male', 19711);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (752027, 'Rebe', 'Community Outreach Specialist', 'Female', 9251);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (703283, 'Templeton', 'Nuclear Power Engineer', 'Male', 43356);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (870197, 'Zelig', 'VP Accounting', 'Male', 38629);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (915648, 'Arleyne', 'Staff Accountant III', 'Female', 21610);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (974733, 'Starlene', 'Occupational Therapist', 'Female', 34969);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (539791, 'Goldarina', 'VP Quality Control', 'Female', 38620);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (945022, 'Tedman', 'Help Desk Technician', 'Male', 40181);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (136467, 'Cristina', 'Statistician I', 'Female', 27695);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (622101, 'Cyrus', 'Director of Sales', 'Male', 21360);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (762191, 'Cammi', 'Cost Accountant', 'Female', 33540);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (110812, 'Urbanus', 'Geological Engineer', 'Male', 19073);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (686383, 'Gottfried', 'Account Coordinator', 'Male', 34630);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (827225, 'Stacee', 'Chemical Engineer', 'Female', 22968);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (152023, 'Neda', 'Analog Circuit Design manager', 'Female', 38146);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (359831, 'Danice', 'Environmental Tech', 'Female', 35587);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (640458, 'Gail', 'Food Chemist', 'Female', 22742);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (260015, 'Brand', 'Staff Scientist', 'Male', 43304);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (290662, 'Willey', 'Graphic Designer', 'Male', 16796);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (997931, 'Lucien', 'Research Assistant II', 'Male', 27626);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (753457, 'Birk', 'Quality Control Specialist', 'Male', 16799);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (160749, 'Mathe', 'Account Executive', 'Male', 40178);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (778832, 'Kandy', 'Associate Professor', 'Female', 11378);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (718521, 'Orrin', 'Senior Cost Accountant', 'Male', 18382);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (139521, 'Yehudi', 'Programmer IV', 'Male', 34734);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (387812, 'Kiley', 'Account Representative II', 'Male', 35646);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (838256, 'Marshal', 'Analyst Programmer', 'Male', 10770);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (227592, 'Sena', 'Software Test Engineer I', 'Female', 10265);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (390850, 'Harwell', 'Nurse', 'Male', 27974);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (885763, 'Benoit', 'Librarian', 'Male', 11254);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (228964, 'Dare', 'Structural Engineer', 'Male', 39293);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (557879, 'Rici', 'Project Manager', 'Female', 24295);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (256600, 'Kimberli', 'Teacher', 'Female', 24467);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (372205, 'Forest', 'Information Systems Manager', 'Male', 34343);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (794983, 'Krystyna', 'Assistant Professor', 'Female', 38922);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (432124, 'Fan', 'Teacher', 'Female', 27553);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (742656, 'Arlin', 'Human Resources Manager', 'Male', 18372);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (181138, 'Mary', 'Human Resources Assistant I', 'Female', 34152);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (269049, 'Petra', 'VP Sales', 'Female', 20975);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (627723, 'Gisella', 'Teacher', 'Female', 22833);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (420496, 'Arlinda', 'Sales Representative', 'Female', 25678);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (603562, 'Lisa', 'Automation Specialist III', 'Female', 41661);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (186475, 'Brien', 'Help Desk Technician', 'Male', 26124);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (735242, 'Monica', 'Chemical Engineer', 'Female', 30154);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (694880, 'Trevor', 'Health Coach IV', 'Male', 26175);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (291948, 'Tabor', 'Environmental Specialist', 'Male', 19396);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (932731, 'Hill', 'Information Systems Manager', 'Male', 22603);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (201524, 'Shannon', 'Administrative Assistant IV', 'Female', 6810);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (616120, 'Barry', 'Business Systems Development Analyst', 'Male', 19374);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (948276, 'Rona', 'Staff Scientist', 'Female', 23884);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (374838, 'Bond', 'Senior Financial Analyst', 'Male', 16187);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (258648, 'Hartley', 'Senior Editor', 'Male', 18188);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (187749, 'Vidovic', 'Analyst Programmer', 'Male', 12809);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (913664, 'Bonnee', 'Paralegal', 'Female', 22817);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (183758, 'Sybille', 'Physical Therapy Assistant', 'Female', 11962);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (163506, 'Arlinda', 'Web Developer I', 'Female', 39652);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (646989, 'Vicky', 'Sales Associate', 'Female', 30493);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (696666, 'Khalil', 'Media Manager III', 'Male', 39687);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (239290, 'Louis', 'Budget/Accounting Analyst IV', 'Male', 25615);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (820848, 'Dorene', 'Staff Accountant IV', 'Female', 11897);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (262577, 'Menard', 'Data Coordiator', 'Male', 23389);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (201150, 'Gilburt', 'Statistician III', 'Male', 9814);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (452348, 'Worth', 'Account Executive', 'Male', 19357);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (213094, 'Park', 'Staff Scientist', 'Male', 41108);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (410945, 'Evelyn', 'Design Engineer', 'Male', 41878);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (887223, 'Smith', 'Administrative Assistant III', 'Male', 44390);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (656540, 'Hamlen', 'Analyst Programmer', 'Male', 24313);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (772655, 'Job', 'Financial Analyst', 'Male', 10573);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (868687, 'Andra', 'Teacher', 'Female', 39282);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (257386, 'Hartwell', 'Research Associate', 'Male', 17915);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (573274, 'Vergil', 'Account Executive', 'Male', 17504);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (602508, 'Lucina', 'Analyst Programmer', 'Female', 17679);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (785422, 'Toddie', 'Registered Nurse', 'Male', 37796);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (636725, 'Roberto', 'Pharmacist', 'Male', 29405);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (834500, 'Row', 'VP Sales', 'Female', 18873);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (637653, 'Lilas', 'Assistant Professor', 'Female', 21513);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (595668, 'Lynna', 'Senior Cost Accountant', 'Female', 6823);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (247064, 'Urson', 'Web Designer IV', 'Male', 28683);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (606318, 'Witty', 'Design Engineer', 'Male', 33546);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (179165, 'Anthe', 'Account Executive', 'Female', 19832);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (500115, 'Natty', 'Data Coordiator', 'Female', 40792);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (110315, 'Pincus', 'Professor', 'Male', 18169);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (396049, 'Gonzales', 'Dental Hygienist', 'Male', 30020);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (623037, 'Mayer', 'Financial Advisor', 'Male', 41392);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (935852, 'Farlay', 'Staff Accountant IV', 'Male', 41781);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (446273, 'Terrel', 'Quality Engineer', 'Male', 34073);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (743282, 'Briggs', 'Operator', 'Male', 27741);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (761495, 'Shurlocke', 'Statistician IV', 'Male', 24537);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (771238, 'Ailee', 'Senior Quality Engineer', 'Female', 12642);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (694261, 'Celka', 'Senior Cost Accountant', 'Female', 13580);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (502748, 'Kip', 'Developer III', 'Female', 9982);
insert into Administration (Adm_ID, Adm_name, Adm_Roll, Adm_gender, Adm_Salary) values (500695, 'Gertie', 'VP Marketing', 'Female', 41756);
