insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (1, 'Poland', 1, 1);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (2, 'Afghanistan', 2, 2);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (3, 'Poland', 3, 3);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (4, 'Russia', 4, 4);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (5, 'Canada', 5, 5);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (6, 'Indonesia', 6, 6);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (7, 'Mongolia', 7, 7);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (8, 'Costa Rica', 8, 8);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (9, 'Vietnam', 9, 9);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (10, 'Bolivia', 10, 10);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (11, 'Indonesia', 11, 11);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (12, 'Ivory Coast', 12, 12);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (13, 'Netherlands', 13, 13);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (14, 'China', 14, 14);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (15, 'Albania', 15, 15);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (16, 'Brazil', 16, 16);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (17, 'China', 17, 17);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (18, 'United Kingdom', 18, 18);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (19, 'Sweden', 19, 19);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (20, 'Portugal', 20, 20);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (21, 'China', 21, 21);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (22, 'Poland', 22, 22);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (23, 'Moldova', 23, 23);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (24, 'Pakistan', 24, 24);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (25, 'El Salvador', 25, 25);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (26, 'Indonesia', 26, 26);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (27, 'Indonesia', 27, 27);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (28, 'South Africa', 28, 28);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (29, 'Poland', 29, 29);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (30, 'Philippines', 30, 30);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (31, 'Honduras', 31, 31);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (32, 'Indonesia', 32, 32);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (33, 'Mauritius', 33, 33);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (34, 'Indonesia', 34, 34);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (35, 'Brazil', 35, 35);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (36, 'Botswana', 36, 36);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (37, 'Indonesia', 37, 37);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (38, 'Philippines', 38, 38);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (39, 'Brazil', 39, 39);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (40, 'United States', 40, 40);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (41, 'Indonesia', 41, 41);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (42, 'Czech Republic', 42, 42);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (43, 'Philippines', 43, 43);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (44, 'China', 44, 44);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (45, 'Portugal', 45, 45);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (46, 'El Salvador', 46, 46);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (47, 'Colombia', 47, 47);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (48, 'China', 48, 48);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (49, 'China', 49, 49);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (50, 'Ukraine', 50, 50);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (51, 'Djibouti', 51, 51);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (52, 'China', 52, 52);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (53, 'Vietnam', 53, 53);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (54, 'Brazil', 54, 54);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (55, 'Bangladesh', 55, 55);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (56, 'South Africa', 56, 56);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (57, 'China', 57, 57);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (58, 'Argentina', 58, 58);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (59, 'Greece', 59, 59);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (60, 'Indonesia', 60, 60);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (61, 'Palestinian Territory', 61, 61);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (62, 'Indonesia', 62, 62);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (63, 'France', 63, 63);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (64, 'Poland', 64, 64);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (65, 'China', 65, 65);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (66, 'Iran', 66, 66);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (67, 'Czech Republic', 67, 67);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (68, 'Indonesia', 68, 68);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (69, 'Brazil', 69, 69);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (70, 'Indonesia', 70, 70);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (71, 'Brazil', 71, 71);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (72, 'Ukraine', 72, 72);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (73, 'France', 73, 73);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (74, 'Indonesia', 74, 74);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (75, 'Tajikistan', 75, 75);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (76, 'China', 76, 76);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (77, 'Sweden', 77, 77);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (78, 'China', 78, 78);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (79, 'Afghanistan', 79, 79);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (80, 'Indonesia', 80, 80);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (81, 'Czech Republic', 81, 81);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (82, 'China', 82, 82);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (83, 'Czech Republic', 83, 83);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (84, 'Croatia', 84, 84);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (85, 'Greece', 85, 85);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (86, 'China', 86, 86);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (87, 'Sweden', 87, 87);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (88, 'Botswana', 88, 88);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (89, 'Indonesia', 89, 89);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (90, 'France', 90, 90);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (91, 'South Africa', 91, 91);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (92, 'Israel', 92, 92);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (93, 'China', 93, 93);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (94, 'Uganda', 94, 94);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (95, 'Philippines', 95, 95);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (96, 'Czech Republic', 96, 96);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (97, 'China', 97, 97);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (98, 'Indonesia', 98, 98);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (99, 'Guatemala', 99, 99);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (100, 'Mongolia', 100, 100);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (101, 'Russia', 101, 101);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (102, 'Sweden', 102, 102);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (103, 'Indonesia', 103, 103);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (104, 'Costa Rica', 104, 104);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (105, 'United States', 105, 105);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (106, 'Poland', 106, 106);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (107, 'France', 107, 107);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (108, 'Malaysia', 108, 108);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (109, 'Philippines', 109, 109);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (110, 'Czech Republic', 110, 110);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (111, 'Uganda', 111, 111);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (112, 'France', 112, 112);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (113, 'Russia', 113, 113);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (114, 'Saint Kitts and Nevis', 114, 114);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (115, 'Norway', 115, 115);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (116, 'Portugal', 116, 116);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (117, 'Madagascar', 117, 117);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (118, 'South Korea', 118, 118);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (119, 'Russia', 119, 119);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (120, 'France', 120, 120);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (121, 'China', 121, 121);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (122, 'Albania', 122, 122);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (123, 'Thailand', 123, 123);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (124, 'Russia', 124, 124);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (125, 'China', 125, 125);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (126, 'Ecuador', 126, 126);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (127, 'Kenya', 127, 127);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (128, 'China', 128, 128);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (129, 'South Korea', 129, 129);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (130, 'Philippines', 130, 130);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (131, 'Brazil', 131, 131);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (132, 'Finland', 132, 132);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (133, 'Armenia', 133, 133);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (134, 'Vietnam', 134, 134);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (135, 'Venezuela', 135, 135);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (136, 'Brazil', 136, 136);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (137, 'China', 137, 137);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (138, 'Norway', 138, 138);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (139, 'Thailand', 139, 139);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (140, 'Sweden', 140, 140);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (141, 'China', 141, 141);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (142, 'Peru', 142, 142);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (143, 'Yemen', 143, 143);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (144, 'Indonesia', 144, 144);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (145, 'Indonesia', 145, 145);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (146, 'China', 146, 146);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (147, 'Botswana', 147, 147);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (148, 'China', 148, 148);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (149, 'Poland', 149, 149);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (150, 'Tunisia', 150, 150);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (151, 'Brazil', 151, 151);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (152, 'Poland', 152, 152);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (153, 'Indonesia', 153, 153);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (154, 'Poland', 154, 154);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (155, 'Portugal', 155, 155);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (156, 'Ukraine', 156, 156);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (157, 'Macedonia', 157, 157);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (158, 'Bosnia and Herzegovina', 158, 158);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (159, 'Ukraine', 159, 159);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (160, 'China', 160, 160);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (161, 'Ecuador', 161, 161);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (162, 'China', 162, 162);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (163, 'Indonesia', 163, 163);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (164, 'China', 164, 164);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (165, 'United States', 165, 165);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (166, 'France', 166, 166);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (167, 'France', 167, 167);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (168, 'Ireland', 168, 168);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (169, 'Afghanistan', 169, 169);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (170, 'Poland', 170, 170);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (171, 'Russia', 171, 171);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (172, 'Tonga', 172, 172);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (173, 'Philippines', 173, 173);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (174, 'China', 174, 174);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (175, 'China', 175, 175);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (176, 'United States', 176, 176);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (177, 'Russia', 177, 177);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (178, 'Greece', 178, 178);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (179, 'Bosnia and Herzegovina', 179, 179);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (180, 'Ukraine', 180, 180);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (181, 'Colombia', 181, 181);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (182, 'Ukraine', 182, 182);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (183, 'Indonesia', 183, 183);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (184, 'Thailand', 184, 184);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (185, 'Guatemala', 185, 185);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (186, 'Guatemala', 186, 186);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (187, 'Canada', 187, 187);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (188, 'United States', 188, 188);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (189, 'Indonesia', 189, 189);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (190, 'North Korea', 190, 190);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (191, 'Indonesia', 191, 191);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (192, 'Japan', 192, 192);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (193, 'Thailand', 193, 193);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (194, 'France', 194, 194);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (195, 'Canada', 195, 195);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (196, 'China', 196, 196);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (197, 'Indonesia', 197, 197);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (198, 'United States', 198, 198);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (199, 'Portugal', 199, 199);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (200, 'Portugal', 200, 200);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (201, 'Czech Republic', 201, 201);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (202, 'Myanmar', 202, 202);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (203, 'Namibia', 203, 203);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (204, 'Uganda', 204, 204);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (205, 'China', 205, 205);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (206, 'Spain', 206, 206);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (207, 'Russia', 207, 207);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (208, 'Sweden', 208, 208);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (209, 'Russia', 209, 209);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (210, 'Philippines', 210, 210);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (211, 'Russia', 211, 211);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (212, 'China', 212, 212);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (213, 'Namibia', 213, 213);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (214, 'Sweden', 214, 214);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (215, 'Lebanon', 215, 215);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (216, 'Sweden', 216, 216);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (217, 'Poland', 217, 217);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (218, 'China', 218, 218);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (219, 'Bulgaria', 219, 219);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (220, 'Argentina', 220, 220);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (221, 'China', 221, 221);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (222, 'Germany', 222, 222);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (223, 'China', 223, 223);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (224, 'Albania', 224, 224);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (225, 'Russia', 225, 225);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (226, 'Sweden', 226, 226);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (227, 'Russia', 227, 227);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (228, 'China', 228, 228);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (229, 'China', 229, 229);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (230, 'Ecuador', 230, 230);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (231, 'Russia', 231, 231);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (232, 'France', 232, 232);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (233, 'Tuvalu', 233, 233);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (234, 'China', 234, 234);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (235, 'China', 235, 235);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (236, 'Australia', 236, 236);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (237, 'Croatia', 237, 237);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (238, 'Afghanistan', 238, 238);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (239, 'Kazakhstan', 239, 239);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (240, 'Poland', 240, 240);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (241, 'Lithuania', 241, 241);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (242, 'Philippines', 242, 242);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (243, 'China', 243, 243);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (244, 'Bhutan', 244, 244);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (245, 'Indonesia', 245, 245);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (246, 'China', 246, 246);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (247, 'Argentina', 247, 247);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (248, 'Sweden', 248, 248);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (249, 'United States', 249, 249);
insert into Buildings (Build_num, Build_name, Build_floors, Build_Exits) values (250, 'Bangladesh', 250, 250);
